### ISSUE TITLE
Hover on "--minor" class on disabled button shows hover button background.

### ISSUE THREAD

**Issue by crowtherdr** [fs-webdev/fs-styles#44]
We already talked to Steven L about this so he will totally remember it.

**Comment by lambertsteven** [comment]
@swordboy1 we've never really implemented a disabled state for minor buttons, is that something we should consider or do we thing that minor buttons shouldn't be disabled? Thoughts?

**Comment by swordboy1** [comment]
@lambertsteven  It's true. We couldn't find an example of a disabled minor button in the product, and we couldn't think of a reason why we would ever need one. That's why we decided that there probably should never be one. That being said, if a case has come up where you feel like you could use one, we could reconsider our previous position.

**Comment by lambertsteven** [comment]
It's only come up with @intervalia (Mike Collins) dialogs. The buttons at the bottom are all disabled when there is an action that isn't cancelable. For example, when you try to add a person in the new Add Person modal flow, if you search for someone and then add them, you can no longer cancel the modal and so all buttons are disabled while the information is sent to the server and back. A lot of times those buttons include minor buttons.

I guess the overall question is whether or not that behavior is viable, and if it is we should probably come up with a disabled style for minor buttons.

**Comment by intervalia** [comment]
This CAN be true for anyone.
We should always avoid making statements like: "we couldn't think of a reason why we would ever need one".
Someone will need it. Just because we can't think of it does not mean it should not be supported.
Buttons CAN de disabled so we need to cover that situation.
It seems to me that we should cover all cases for all buttons:

Normal
Normal:hover
Disabled
Disabled:hover

There might even be more than these.

But all cases that can be used need to be supported.

**Comment by lambertsteven** [comment]
fixed by #48
